version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: noclick
      POSTGRES_PASSWORD: noclick
      POSTGRES_DB: financial_control
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: